#This file was originally generated by NovalIDE's unitest wizard
import unittest
import userdb
import time

class TestUserDataDb(unittest.TestCase):
    def setUp(self):
        self.db = userdb.UserDataDb.get_db()
    def tearDown(self):
        pass

    def testget_db(self):
        pass

    def testinit_data_db(self):
        pass

    def testCreateUser(self):
        pass

    def testGetUser(self):
        self.db.SubmitAllRecords()
        #self.db.GetUser()
        self.db.RecordStart()
        time.sleep(5)
        #self.db.RecordEnd()
        #self.db.QueryRecord()


if __name__ == "__main__":
    unittest.main()
