

NODE_MODULE_TYPE = 1
NODE_FUNCDEF_TYPE = 2
NODE_CLASSDEF_TYPE = 3
NODE_CLASS_PROPERTY = 4
NODE_OBJECT_PROPERTY = 5
NODE_IMPORT_TYPE = 6
NODE_FROMIMPORT_TYPE = 7
NODE_UNKNOWN_TYPE = 7


PROPERTY_TYPE_UNKNOWN = -1
PROPERTY_TYPE_INT = 0
PROPERTY_TYPE_STR = 1
PROPERTY_TYPE_MODULE = 2
PROPERTY_TYPE_LIST =3
PROPERTY_TYPE_TUPLE = 3
PROPERTY_TYPE_DICT = 5
PROPERTY_TYPE_OBJECT = 6
PROPERTY_TYPE_FLOAT = 7
PROPERTY_TYPE_LONG = 8
PROPERTY_TYPE_BOOL = 9

LANG_NONE_LEXER = 0
LANG_PYTHON_LEXER = 1
LANG_C_LEXER = 2
LANG_HTML_LEXER = 3
LANG_XML_LEXER = 4