DATABASE_VERSION = "1.0.2"

NODE_MODULE_TYPE = 1
NODE_FUNCDEF_TYPE = 2
NODE_CLASSDEF_TYPE = 3
NODE_CLASS_PROPERTY = 4
NODE_OBJECT_PROPERTY = 5
NODE_IMPORT_TYPE = 6
NODE_FROMIMPORT_TYPE = 7
NODE_ASSIGN_TYPE = 8
NODE_ARG_TYPE = 9
NODE_UNKNOWN_TYPE = 1001


ASSIGN_TYPE_UNKNOWN = -1
ASSIGN_TYPE_INT = 0
ASSIGN_TYPE_STR = 1
ASSIGN_TYPE_MODULE = 2
ASSIGN_TYPE_LIST =3
ASSIGN_TYPE_TUPLE = 4
ASSIGN_TYPE_DICT = 5
ASSIGN_TYPE_OBJECT = 6
ASSIGN_TYPE_FLOAT = 7
ASSIGN_TYPE_LONG = 8
ASSIGN_TYPE_BOOL = 9
ASSIGN_TYPE_SET = 10
ASSIGN_TYPE_OBJECT = 11
ASSIGN_FILE_OBJECT = 12

LANG_NONE_LEXER = 0
LANG_PYTHON_LEXER = 1
LANG_C_LEXER = 2
LANG_HTML_LEXER = 3
LANG_XML_LEXER = 4